### ISSUE TITLE
Make a select all button

### ISSUE THREAD

**Issue by quitequinn** [anicollection/anicollection.github.io#1]
`$('.caption[title="Add"]').trigger('click');`

That way I don't have to type it in the console

**Comment by quitequinn** [comment]
... it would also be nice if you had a link to your git repo

**Comment by darielnoel** [comment]
Hi Quinn, thanks a lot for your feedback :). I think that the "Select All" could be a great feature. However,  before add it, we need to take into account a couple of things which I would like to share with you, for find a solution together.
- Network Performance

As you can see, AniCollection has not a backend. Every time that we Add a new Animation, we need to retrieve a db_animation_name.json which was generated statically previously. When we make something like the code below we are making a hard numbers of requests.

``` javascript
$('.caption[title="Add"]').trigger('click');
```

In my opinion the **clear solution** is make a backend, but I don't have money for that right now. We are looking for donations in Kickstarter, also we are looking for some companies for partnership, but by the moment we can't do it.

The **other solution** could be generate an entire file with all animation previously, and make a link to it. And when the people make "Select All", they can download or see the entire file. I think that could be a great solution by the moment. What do you think?
- UI interface

I am looking the interface many times and I can't find a nice place to put the "Select All" button. Any idea?

Thanks again for the feedback :). You will always welcome to collaborate.

Best Regards, Dariel

**Comment by quitequinn** [comment]
I'm not sure how your logic works... but I'm sure there is a simple way to update your counter in one request... I just did that for simplicity.
AND IF NOT ok so it makes 72 requests... I would be a little surprised if that kills your site... 

BUT if I were you I would just link to a public git of all the animations. Most devs are going to prefer a git rather than a separate site anyway... that way they don't need to clog up their bookmarks.

What I wouldn't do is have a button that says it does one thing and actually does another... especially since your saving our count when we navigate away.

Anyways maybe the button could be something like this..
![image](https://cloud.githubusercontent.com/assets/2885870/6701194/af44faf0-ccd6-11e4-912a-a09819cd7d17.png)

**Comment by darielnoel** [comment]
Update the counter is not a problem. The 72 request yes because if we follow adding animations this number will be bigger. However I am going to follow your advice, by the moment 72 is not a big number. 

I will propose to put the button here:

![addall](https://cloud.githubusercontent.com/assets/3312990/6701953/1a9b6f28-ccfa-11e4-93d2-d03c9ba9c621.png)

What are you think?

**Comment by darielnoel** [comment]
Thanks :) @quitequinn 

https://twitter.com/dariel_noel/status/578049326577930241

**Comment by quitequinn** [comment]
looks/works great @darielnoel 

ps. I'm a he not a she
